# Generated by Django 2.2.5 on 2019-10-03 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tindakan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('prioritas', models.CharField(choices=[('mendesak', 'mendesak'), ('normal', 'normal')], max_length=255)),
                ('content', models.TextField(blank=True, max_length=1000, verbose_name='content')),
                ('dokumen', models.FileField(blank=True, null=True, upload_to='media/')),
                ('status_terima', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('sent', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('Sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('assign_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assign_to', to=settings.AUTH_USER_MODEL)),
                ('tindakan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='section.Tindakan')),
            ],
        ),
    ]
