# Generated by Django 2.2.5 on 2019-09-23 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('employe', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tindakan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('prioritas', models.CharField(choices=[('mendesak', 'mendesak'), ('normal', 'normal')], max_length=255)),
                ('content', models.TextField()),
                ('dokumen', models.FileField(blank=True, null=True, upload_to='')),
                ('status_terima', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('assign_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assign_to', to='section.Sections')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='section.Sections')),
                ('tindakan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.Tindakan')),
            ],
        ),
    ]
