# Generated by Django 2.2.5 on 2019-10-03 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='status_terima',
        ),
    ]
