# Generated by Django 2.2.5 on 2019-09-23 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='tindakan',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='section.Tindakan'),
        ),
    ]
