# Generated by Django 2.2.5 on 2019-09-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0002_auto_20190923_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='content',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='content'),
        ),
    ]
