# Generated by Django 2.2.5 on 2019-10-03 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0002_remove_ticket_status_terima'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status_terima',
            field=models.BooleanField(default=False),
        ),
    ]
