# Generated by Django 2.2.5 on 2019-09-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0003_auto_20190923_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='content',
            field=models.TextField(blank=True, default=1, max_length=1000, verbose_name='content'),
            preserve_default=False,
        ),
    ]
