# Generated by Django 2.2.5 on 2019-09-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0006_auto_20190923_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
